version = 1

exclude_patterns = [
  "**/input.ts",
  "**/*-input.ts",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = [
    "nodejs",
    "browser",
    "vitest",
    "cypress"
  ]
